/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./view/GameView"
import SceneCamera from "./view/SceneCamera"
import MainView from "./view/MainView"
import GameUI from "./view/GameUI"
import DeviceItem from "./ui/DeviceItem"
import DeviceList from "./ui/DeviceList"
import MainHall from "./view/MainHall"
import Device from "./script/Device"
import CustomerMgt from "./script/CustomerMgt"
import Customer from "./script/Customer"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("view/GameView.js",GameView);
		reg("view/SceneCamera.js",SceneCamera);
		reg("view/MainView.js",MainView);
		reg("view/GameUI.js",GameUI);
		reg("ui/DeviceItem.js",DeviceItem);
		reg("ui/DeviceList.js",DeviceList);
		reg("view/MainHall.js",MainHall);
		reg("script/Device.js",Device);
		reg("script/CustomerMgt.js",CustomerMgt);
		reg("script/Customer.js",Customer);
    }
}
GameConfig.width = 750;
GameConfig.height = 1624;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Game.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
