/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./view/GameView"
import SceneCamera from "./view/SceneCamera"
import GameUI from "./view/GameUI"
import Test from "./script/Test"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("view/GameView.js",GameView);
		reg("view/SceneCamera.js",SceneCamera);
		reg("view/GameUI.js",GameUI);
		reg("script/Test.js",Test);
    }
}
GameConfig.width = 750;
GameConfig.height = 1624;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Game.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
